version: '3'

x-gpu: &USE_GPU
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['all']
            capabilities: [gpu]

services:
  train:
    <<: *USE_GPU
    build: .
    image: cohakim/sd-scripts:latest
    shm_size: '2gb'
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ./config:/config
      - ./training_data:/training_data
      - ./output:/output
    environment:
      - DATASET=$DATASET
    entrypoint: |
      /bin/bash -c "
        poetry run accelerate launch \\
          --config_file accelerate.config \\
          --num_cpu_threads_per_process 1 \\
          train_network.py \\
          --config_file=/training_data/dataset/$${DATASET}/config.toml \\
          --dataset_config=/training_data/dataset/$${DATASET}/dataset.toml
      "

volumes:
  huggingface_cache:
