version: '3'

x-gpu: &USE_GPU
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['all']
            capabilities: [gpu]

services:
  train:
    <<: *USE_GPU
    build: .
    image: cohakim/sd-scripts:latest
    shm_size: '2gb'
    volumes:
      - sd-scripts:/sd-scripts
      - ./training_data:/training_data
    entrypoint: |
      /bin/bash -c "
        eval poetry run $(cat /services/train/config/run.command)
      "

volumes:
  sd-scripts:
