version: '3'

x-gpu: &USE_GPU
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['all']
            capabilities: [gpu]

services:
  train:
    <<: *USE_GPU
    build: .
    image: cohakim/sd-scripts:latest
    shm_size: '2gb'
    volumes:
      - tokenizer_cache:/root/.cache/tokenizer_cache
      - ./config:/config
      - ./training_data:/training_data
      - ./output:/output
    entrypoint: |
      /bin/bash -c "
        eval poetry run $(cat /config/run.command)
      "

volumes:
  tokenizer_cache:
