version: '3'

x-gpu: &USE_GPU
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['all']
            capabilities: [gpu]

services:
  train:
    <<: *USE_GPU
    build: .
    image: cohakim/sd-scripts:latest
    shm_size: '2gb'
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ./config:/config
      - ./training_data:/training_data
      - ./output:/output
    entrypoint: '/bin/bash -c /sd-scripts/entrypoint.sh'

volumes:
  huggingface_cache:
